FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the rest (will still mount as a volume in docker-compose)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
