services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # helps hot reload inside Docker
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - ETHERPAD_API_KEY=${ETHERPAD_API_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "5001:5000"
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway
    command: migrate 
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_CONNECT_RETRIES=60
    depends_on:
      - db

  etherpad:
    image: etherpad/etherpad
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - etherpad-data:/opt/etherpad-lite/var
      - ./etherpad/settings.json:/opt/etherpad-lite/settings.json
    environment:
      - ETHERPAD_API_KEY=${ETHERPAD_API_KEY}
      - ETHERPAD_ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}
      - ETHERPAD_TITLE=CoLab Code Etherpad
  db:
    image: postgres:latest
    restart: always
    environment:
      # Reference the variables from the .env file
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  etherpad-data:
  postgres_data: